round rounds are rounder than rough edges
creelonestudios/songguesser pull request #33
Opened 2022-06-19 19:30 UTC by j0code

2022-06-20 13:45 UTC, j0code commented
> is there sth that still has to be done on this?

suppose you don't wanna branch f-rounds-cmd off this branch, I don't think so

2022-06-20 13:45 UTC, cfpwastaken commented
?

2022-06-20 13:46 UTC, cfpwastaken commented
![image](https://user-images.githubusercontent.com/44261356/174615575-4d61d1ea-1ee7-4771-ac92-0f61bfe9f95f.png)

2022-06-20 14:28 UTC, cfpwastaken approved these changes
![approved](https://user-images.githubusercontent.com/44261356/174623917-bfbf97ff-31f0-46ed-900c-311a8434f160.gif)

2022-06-20 20:41 UTC, j0code commented
![image](https://user-images.githubusercontent.com/42189560/174675026-be40a10b-ffe2-4da7-b4d7-b38a4a1b5dd9.png)
I did some more changes :)

2022-06-30 15:48 UTC, cfpwastaken requested changes

2022-06-30 15:48 UTC, cfpwastaken commented on lyrics.js
> +					i.reply({ content: "You alr joined. The Game will start soon.", ephemeral: true })
make this `already` pls

2022-07-02 18:47 UTC, cfpwastaken approved these changes
Yes.

2022-07-02 18:52 UTC, cfpwastaken commented
You can merge it, ill do the command stuff later.

2022-08-25 16:42 UTC, merged